---
- name: Setup PostgreSQL Machine
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
    user: "{{ web_app_user }}"
  pre_tasks:
    - name: install python-ipaddress
      apt:
        name: python-ipaddress
        state: present
        update_cache: yes
      become: yes
  roles:
    - role: ansible-secure
      vars:
        secure_deployment_user: "{{ user }}"
    - role: ansible-postgres
      vars:
        postgres_cluster_name: main
        postgres_enable_backups: true
        postgres_install_ppa: true
        postgres_user: "{{ user }}"
        postgres_version: 11
        postgres_whitelist_ip: "{{ web_app_ip }}"
